# Getting and Cleaning Data Course Project - Code Book

## Data Source

This data is taken from the UC Irvine Machine Learning Repository.  The original source and 
description of the data can be found here:

* Data - https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip
* Description - http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

## Background 

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data.

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.

## Description of Data Input

Detailed information can be found in the README file contained within the downloaded UCI HAR Dataset folder

- 'features_info.txt': Shows information about the variables used on the feature vector.

- 'features.txt': List of all features.

- 'activity_labels.txt': Links the class labels with their activity name.

- 'train/X_train.txt': Training set.

- 'train/y_train.txt': Training labels.

- 'test/X_test.txt': Test set.

- 'test/y_test.txt': Test labels.

The following files are available for the train and test data. Their descriptions are equivalent. 

- 'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30. 

- 'train/Inertial Signals/total_acc_x_train.txt': The acceleration signal from the smartphone accelerometer X axis in standard gravity units 'g'. Every row shows a 128 element vector. The same description applies for the 'total_acc_x_train.txt' and 'total_acc_z_train.txt' files for the Y and Z axis. 

- 'train/Inertial Signals/body_acc_x_train.txt': The body acceleration signal obtained by subtracting the gravity from the total acceleration. 

- 'train/Inertial Signals/body_gyro_x_train.txt': The angular velocity vector measured by the gyroscope for each window sample. The units are radians/second. 

## Description of Data Output

The tidy_data.txt file contains observations on the following parameters:

* subject - Identifier of subject
* activity - Type of activity: WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING
* timeBodyAcceleration.mean-XYZ - mean time to obtain body acceleration signals
* timeGravityAcceleration.mean-XYZ - mean time to obtain gravity acceleration signals
* timeBodyAccelerationJerk-XYZ - mean time to obtain body acceleration jerk signals
* timeBodyVelocity.mean-XYZ - mean time to obtain body velocity signals
* timeBodyVelocityJerk.mean-XYZ - mean time to obtain body velocity jerk signals
* timeBodyAccelerationMagnitude.mean - mean time to obtain body acceleration magnitude signals
* timeGravityAccelerationMagnitude.mean - mean time to obtain gravity acceleration magnitude signals
* timeBodyAccelerationJerkMagnitude.mean - mean time to obtain body acceleration jerk magnitude signals 
* timeBodyVelocityMagnitude.mean - mean time to obtain body velocity magnitude signals
* timeBodyVelocityJerkMagnitude.mean - mean time to obtain body velocity jerk magnitude signals
* frequencyBodyAcceleration.mean-XYZ - mean frequency of body acceleration signals
* frequencyBodyAccelerationJerk.mean-XYZ - mean frequency of body acceleration jerk signals
* frequencyBodyVelocity.mean-XYZ - mean frequency of body velocity signals
* frequencyBodyAccelerationMagnitude.mean - mean frequency of body acceleration magnitude signals
* frequencyBodyBodyAccelerationJerkMagnitude.mean - mean frequency of BodyBody acceleration jerk magnitude signals 
* frequencyBodyBodyVelocityMagnitude.mean - mean frequency of BodyBody velocity magnitude signals
* frequencyBodyBodyVelocityJerkMagnitude.mean - mean frequency of BodyBody velocity jerk magnitude signals
* timeBodyAcceleration.std-XYZ - standard deviation of time to obtain body acceleration signals
* timeGravityAcceleration.std-XYZ - standard deviation of time to obtain body acceleration signals
* timeBodyAccelerationJerk.std-XYZ - standard deviation of time to obtain body acceleration jerk signals
* timeBodyVelocity.std-XYZ - standard deviation of time to obtain body velocity signals
* timeBodyVelocityJerk.std-XYZ - standard deviation of time to obtain body velocity jerk signals 
* timeBodyAccelerationMagnitude.std - standard deviation of time to obtain body acceleration magnitude signals
* timeGravityAccelerationMagnitude.std - standard deviation of time to obtain gravity acceleration magnitude signals
* timeBodyAccelerationJerkMagnitude.std - standard deviation of time to obtain body acceleration jerk magnitude signals 
* timeBodyVelocityMagnitude.std- standard deviation of time to obtain body velocity magnitude signals
* timeBodyVelocityJerkMagnitude.std - standard deviation of time to obtain body velocity jerk magnitude signals 
* frequencyBodyAcceleration.std-XYZ - standard deviation of frequency of body acceleration signals 
* frequencyBodyAccelerationJerk.std-XYZ - standard deviation of frequency of body acceleration jerk signals 
* frequencyBodyVelocity.std-XYZ - standard deviation of frequency of body velocity signals
* frequencyBodyAccelerationMagnitude.std - standard deviation of frequency of body acceleration magnitude signals 
* frequencyBodyBodyAccelerationJerkMagnitude.std - standard deviation of frequency of BodyBody acceleration jerk magnitude signals
* frequencyBodyBodyVelocityMagnitude.std - standard deviation of frequency of BodyBody velocity magnitude signals 
* frequencyBodyBodyVelocityJerkMagnitude.std - standard deviation of frequency of BodyBody velocity jerk magnitude signals


